apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sre

bases:
  - ../base

patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/labels/0
        value: staging
    target:
      kind: RunnerDeployment
